#!/usr/bin/env bash
# Bash script that displays numbers 1..100 and prints key words based on if the number is a multiple of 3 and/or 5.
count=1
until [ "$count" -eq 101 ]; do
	if ((count%3==0 && count%5==0)); then
		echo "FizzBuzz"
	elif ((count%3==0)); then
		echo "Fizz"
	elif ((count%5==0)); then
		echo "Buzz"
	else
		echo "$count"
	fi
	((count++))
done
