#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd, but with select fields only.
file=$(cat /etc/passwd)
while $file; do
	usrname_usrid_home=$(echo "$file" | cut -d ':' -f1,3,6-)
	echo "$usrname_usrid_home"
done
