#!/user/bin/env bash
# Bash script that displays the content of the file /etc/passwd, but with select fields only.
for file in /etc/passwd; do
	if [ "$file" ]; then
		list=$(cat $file)
		usrname_usrid_home=$(echo $list | cut -d ':' -f1,3,6-)
		echo "$usrname_usrid_home"
	fi
done
