#!/usr/bin/env bash
# Bash script that displays the visitor IP along with the HTTP status code from the Apache log file.
curl -O http://intranet-projects-files.s3.amazonaws.com/holbertonschool-sysadmin_devops/80/apache-access.log > apache-access.log
log_file="apache-acces.log"
awk '{print $1, $9}' "$log_file
