#!/usr/bin/env bash
# Bash script that displays the visitor IP along with the HTTP status code from the Apache log file.
log_file="apache-access.log"
if [ -e "$log_file" ]; then
	awk '{print $1 " " $9}' "$log_file"
fi
