#!/usr/bin/env bash
# Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
i=1
if [ $i -eq 9 ]
do
	echo "Best School\n Hi"
	while [ $i -le 10 ]
	do
		echo "Best School"
		(($i++))
	done
fi
