#!/usr/bin/env bash
# Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
NUM=1
while [ $NUM -le 10 ]
do
	echo "Best School"
	if [ $NUM -eq 9 ]
	then
		echo "Best School\n Hi"
		(($NUM++))
	fi
done
