#!/usr/bin/env bash
# Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
NUM=0
while (($NUM<=9))
do
	echo "Best School"
	(($NUM++))
	if (($NUM=8))
	then
		echo "\n Hi"
	fi
done
