#!/usr/bin/env bash
# Bash script using while loop and case statements
NUM=1
while [ $NUM -le 20 ]; do
	case $NUM in
		4) echo -e "$NUM\nbad luck from China";;
		9) echo -e "$NUM\nbad luck from Japan";;
		17) echo -e "$NUM\nbad luck from Italy";;
		*) echo $NUM
	esac
	((NUM++))
done
